# Generated by Django 4.2.3 on 2023-07-21 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='priorty',
            new_name='priority',
        ),
    ]
