# Generated by Django 4.2.3 on 2023-07-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_rename_priorty_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1997-10-18'),
            preserve_default=False,
        ),
    ]
